---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggmap)
library(sf)
library(ggthemes)

load("~/Dropbox/DataScience/R/kohanimed/output/algandmed.RData")
```

```{r}
linn_vald <- kohanimed %>% 
  filter(nimeobjekti_liik %in% c("vald", "linn"))
```

```{r}
# Funktsioon, mis teisendab route(output = "all") funktsiooni tuemuse lat/lon dataframeks
# Võetud: http://s4rdd.blogspot.com/2012/12/google-maps-api-decoding-polylines-for.html
decodeLine <- function(encoded){
    require(bitops)
    
    vlen <- nchar(encoded)
    vindex <- 0
    varray <- NULL
    vlat <- 0
    vlng <- 0
    
    while(vindex < vlen){
        vb <- NULL
        vshift <- 0
        vresult <- 0
        repeat{
            if(vindex + 1 <= vlen){
                vindex <- vindex + 1
                vb <- as.integer(charToRaw(substr(encoded, vindex, vindex))) - 63  
            }
            
            vresult <- bitOr(vresult, bitShiftL(bitAnd(vb, 31), vshift))
            vshift <- vshift + 5
            if(vb < 32) break
        }
        
        dlat <- ifelse(
            bitAnd(vresult, 1)
            , -(bitShiftR(vresult, 1)+1)
            , bitShiftR(vresult, 1)
        )
        vlat <- vlat + dlat
        
        vshift <- 0
        vresult <- 0
        repeat{
            if(vindex + 1 <= vlen) {
                vindex <- vindex+1
                vb <- as.integer(charToRaw(substr(encoded, vindex, vindex))) - 63        
            }
            
            vresult <- bitOr(vresult, bitShiftL(bitAnd(vb, 31), vshift))
            vshift <- vshift + 5
            if(vb < 32) break
        }
        
        dlng <- ifelse(
            bitAnd(vresult, 1)
            , -(bitShiftR(vresult, 1)+1)
            , bitShiftR(vresult, 1)
        )
        vlng <- vlng + dlng
        
        varray <- rbind(varray, c(vlat * 1e-5, vlng * 1e-5))
    }
    coords <- data.frame(varray)
    names(coords) <- c("lat", "lon")
    coords
}
```


```{r}
teekond_laulasmaale <- function(kohanimi){
  tryCatch(
    {
      rada <- route(from = kohanimi, to = "Juku, Laulasmaa", structure = "route", output = "all")
      
      rada_df <- decodeLine(rada$routes[[1]]$overview_polyline$points) %>%
        mutate(lahtepunkt = kohanimi)
    }, error=function(e) NULL
  )
}
```

```{r}
teekonnad <- map_df(linn_vald$kohanimi, teekond_laulasmaale)
```


```{r}
# save(teekonnad, file = "output/teekonnad.RData")
```


Joonista Eesti kaardile kõik teed Laulasmaale
```{r}
# Eesti koordinaadid
estonia <- c(left = 21.468793, bottom = 57.493472, right = 28.192426, 
             top = 59.689290)

# Eesti aluskaart
eesti_kaart <- get_map(estonia, zoom = 8, maptype = "toner-background")

laulasmaa <- geocode("Juku, Laulasmaa")

# salvest sõidud kaardile
png(filename = "output/koik_teed_laulasmaale.png", width = 950, height = 600)
ggmap(eesti_kaart, darken = 0.7) +  # alusaakrt tumedat tooni 
  geom_path(data = teekonnad, aes(x = lon, y = lat, group = lahtepunkt), 
              colour = "#FFFF33", alpha = 0.4) +  # joonesd kollased ja peenikesed
  theme_map() +
  geom_point(data = laulasmaa, aes(x = lon, y = lat),
             colour = "red", size = 5)
dev.off()
```

